version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: hemanthkumar75/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  backend:
    image: hemanthkumar75/backend:v1
    container_name: backend
    depends_on:
      - mysql
    command: sh -c "sleep 10 && node /opt/server/index.js"
  frontend:
    image: hemanthkumar75/frontend:v1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:8080